sudo: true
dist: trusty

before_install:
  - sudo apt-get --yes install snapd
  - sudo snap install hugo

script:
  - /snap/bin/hugo

deploy:
  local_dir: public 
  repo: foxtrotcharlie1337/foxtrotcharlie1337.github.io
  target_branch: master 
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  name: "foxtrotcharlie1337"
  on:
    branch: master

